# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 01:43
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='default_thumb',
            field=models.TextField(null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AddField(
            model_name='post',
            name='video_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
