# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 01:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170712_0143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='data_json',
        ),
    ]
