# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 02:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170712_0254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='api_name',
            new_name='provider',
        ),
    ]
